baseURL: "https://merry-croquembouche-b1471e.netlify.app/"
languageCode: en-us
title: My New Hugo Site
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog. Here you'll find my site contents

  socialIcons:
    - name: Facebook
      url: "https://facebook.com"
    - name: Github
      url: "https://github.com"


  cover: 
    linkFullImageS: 
    
  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20

    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30

    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40


